// <auto-generated />
namespace Film_Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class film : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(film));
        
        string IMigrationMetadata.Id
        {
            get { return "202206052116583_film"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
