// <auto-generated />
namespace Film_Passion_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ActorsFilms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActorsFilms));
        
        string IMigrationMetadata.Id
        {
            get { return "202206052346453_ActorsFilms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
